Fall 2015 Schedule (Mobile/Single Column Format)
==================================================

The following courses will (tentatively) be held during the Fall 2015 semester.

For classroom locations and open/full status, see 
`LOCUS <http://www.luc.edu/locus>`_.

Note: While we update this page regularly, please check 
`LOCUS <http://www.luc.edu/locus>`_ for the most recent information.

**In case of conflict, information on LOCUS should be considered authoritative.**

See `Textbook Information <https://docs.google.com/spreadsheets/d/1EecgbxCW0efku2_yaGrhOEwznoj9eGTJI01dOJgQ1R8/edit#gid=0>`_.

Alternate wide screen format page: :doc:`fallwidescreen`.

Headings in this Page
~~~~~~~~~~~~~~~~~~~~~~~~~~

* :ref:`fallm_undergraduate_courses_list`
* :ref:`fallm_graduate_courses_list`
* :ref:`fallm_csis_courses_list`

.. _fallm_undergraduate_courses_list:

Undergraduate Courses
~~~~~~~~~~~~~~~~~~~~~

COMP111-01W: History of Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: George Thiruvathukal

Location: LSC

Schedule: 12:35:00 PM - 1:25:00 PM (MWF) 

Course Description: :doc:`comp111`

COMP125-001: Visual Information Processing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman

Location: LSC

Schedule: 1:00:00 PM - 2:15:00 PM (TTr) 

Course Description: :doc:`comp125`

COMP125-002: Visual Information Processing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman

Location: LSC

Schedule: 4:15:00 PM - 6:45:00 PM (T) 

Course Description: :doc:`comp125`

Info: *Tentative, may not be offered*

COMP150-001: Introduction to Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Dima Dligach

Location: LSC

Schedule: 2:45:00 PM - 4:00:00 PM (MW) 

Course Description: :doc:`comp150`

COMP150-002: Introduction to Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan

Location: LSC

Schedule: 11:30:00 AM - 12:45:00 PM (TTr) 

Course Description: :doc:`comp150`

COMP150-003: Introduction to Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Grace (PT) Hopper

Location: LSC

Schedule: 12:35:00 PM - 1:25:00 PM (MWF) 

Course Description: :doc:`comp150`

COMP163-001: Discrete Structures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg

Location: LSC

Schedule: 11:30:00 AM - 12:20:00 PM (MWF) 

Course Description: :doc:`comp163`

COMP163-002: Discrete Structures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ada (PT) Lovelace

Location: LSC

Schedule: 4:15:00 PM - 5:30:00 PM (MW) 

Course Description: :doc:`comp163`

COMP163-003: Discrete Structures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ada (PT) Lovelace

Location: LSC

Schedule: 6:00:00 PM - 7:15:00 PM (MW) 

Course Description: :doc:`comp163`

COMP170-001: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis

Location: LSC

Schedule: 10:00:00 AM - 11:15:00 AM (TTr) 

Course Description: :doc:`comp170`

COMP170-002: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis

Location: LSC

Schedule: 1:00:00 PM - 2:15:00 PM (TTr) 

Course Description: :doc:`comp170`

COMP170-003: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig

Location: LSC

Schedule: 2:30:00 PM - 3:45:00 PM (TTr) 

Course Description: :doc:`comp170`

COMP170-004: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig

Location: LSC

Schedule: 4:15:00 PM - 6:45:00 PM (T) 

Course Description: :doc:`comp170`

COMP170-01L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis

Location: LSC

Schedule: 11:15:00 AM - 11:40:00 AM (TTr) 

Course Description: :doc:`comp170`

COMP170-02L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis

Location: LSC

Schedule: 12:35:00 PM - 1:00:00 PM (TTr) 

Course Description: :doc:`comp170`

COMP170-03L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig

Location: LSC

Schedule: 3:45:00 PM - 4:05:00 PM (TTr) 

Course Description: :doc:`comp170`

COMP170-04L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig

Location: LSC

Schedule: 7:00:00 PM - 7:50:00 PM (T) 

Course Description: :doc:`comp170`

COMP215-001: Object Oriented Programming with Mathematics
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Christine A Haught

Location: LSC

Schedule: 2:30:00 PM - 3:45:00 PM (TTr) 

Course Description: :doc:`comp215`

COMP250-01W: Introduction to Scientific and Technical Communication
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Roxanne Schwab

Location: LSC

Schedule: 2:45:00 PM - 4:00:00 PM (MW) 

Course Description: :doc:`comp250`

COMP251-001: Introduction to Database Systems
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Guy Bevente

Location: LSC

Schedule: 7:00:00 PM - 9:30:00 PM (M) 

Course Description: :doc:`comp251`

COMP264-001: Introduction to Computer Systems
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg

Location: LSC

Schedule: 10:25:00 AM - 11:15:00 AM (MWF) 

Course Description: :doc:`comp264`

COMP271-001: Data Structures: Algorithms and Applications
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan

Location: WTC

Schedule: 2:30:00 PM - 3:45:00 PM (TTr) 

Course Description: :doc:`comp271`

COMP271-002: Data Structures: Algorithms and Applications
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Maria Del Carmen Saenz

Location: LSC

Schedule: 6:00:00 PM - 8:30:00 PM (Tr) 

Course Description: :doc:`comp271`

COMP271-01L: Data Structures: Algorithms and Applications
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan

Location: WTC

Schedule: 3:45:00 PM - 4:05:00 PM (TTr) 

Course Description: :doc:`comp271`

COMP271-02L: Data Structures: Algorithms and Applications
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Maria Del Carmen Saenz

Location: LSC

Schedule: 8:30:00 PM - 9:20:00 PM (Tr) 

Course Description: :doc:`comp271`

COMP312-01E: Free/Open Source Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: George Thiruvathukal

Location: ONLN

Schedule:  -  () 

Course Description: :doc:`comp312`

Note: This is an online class that includes synchronous and asynchronous
interaction among students and Instructor.   All sessions will be recorded.
Specific synchronous meetings will be scheduled in consultation with students

COMP313-001: Intermediate Object-Oriented Development
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer

Location: LSC

Schedule: 2:45:00 PM - 5:15:00 PM (W) 

Course Description: :doc:`comp313`

COMP314-001: Problem Solving Seminar I
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington

Location: See below

Schedule: See below

Course Description: :doc:`comp314-315`

There will be one organizational meeting Monday August 24, 3-4PM in LT 410, 
to agree on 5 weekend practice times through the end of October. 
See the `Programming Team <http://anh.cs.luc.edu/314-315/prog-team.html>`_, 
particularly if you cannot attend the organizational session.


COMP315-001: Problem Solving Seminar II
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington

Location: See below

Schedule: See below

Course Description: :doc:`comp314-315`

There will be one organizational meeting Monday August 24, 3-4PM in LT 410, 
to agree on 5 weekend practice times through the end of October. 
See the `Programming Team <http://anh.cs.luc.edu/314-315/prog-team.html>`_, 
particularly if you cannot attend the organizational session.

COMP317-001: Social, Legal, and Ethical Issues in Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Matthew Paul Butcher

Location: LSC

Schedule: 7:00:00 PM - 9:30:00 PM (T) 

Course Description: :doc:`comp317`

COMP320-001: Software Systems Analysis
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Conrad Weisert

Location: WTC

Schedule: 4:15:00 PM - 6:45:00 PM (M) 

Course Description: :doc:`comp320`

COMP331-001: Cryptography
~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Stephen Doty

Location: LSC

Schedule: 9:20:00 AM - 10:10:00 AM (MWF) 

Course Description: :doc:`comp331`

COMP336-001: Markup Languages
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Matthew William Bone

Location: WTC

Schedule: 7:00:00 PM - 9:30:00 PM (W) 

Course Description: :doc:`comp336`

COMP343-001: Intro to Computer Networks
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal

Location: WTC

Schedule: 4:15:00 PM - 6:45:00 PM (T) 

Course Description: :doc:`comp343`

COMP343-002: Intro to Computer Networks
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal

Location: ONLN

Schedule:  -  () 

Course Description: :doc:`comp343`

Note: This is an online class that includes 
synchronous and asynchronous interaction 
among students and instructor. Participation
in synchronous sessions is strongly recommended.

COMP347-001: Intrusion Detection and Computer Security
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz

Location: WTC

Schedule: 5:45:00 PM - 8:15:00 PM (F) 

Course Description: :doc:`comp347`

COMP347-002: Intrusion Detection and Computer Security
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz

Location: ONLN

Schedule:  -  () 

Course Description: :doc:`comp347`

Note: This is an online class. The classroom session will be broadcast live on
Friday evenings via AdobeConnect allowing online student interaction.  Sessions
will also be recorded and made available. Students may participate
synchronously or asynchronously at their discretion.

COMP363-001: Desgn and Analysis Computer Algorithms
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert

Location: LSC

Schedule: 2:45:00 PM - 5:15:00 PM (M) 

Course Description: :doc:`comp363`

COMP364-001: High-Performance Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Sharan Kalwani

Location: WTC

Schedule: 7:00:00 PM - 9:30:00 PM (W) 

Course Description: :doc:`comp364`

COMP374-001: Intro to Operating Systems
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Joseph Paul Kaylor

Location: LSC

Schedule: 7:00:00 PM - 9:30:00 PM (M) 

Course Description: :doc:`comp374`

COMP381-001: Bioinfomatics
~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor:  Heather Wheeler

Location: LSC

Schedule: 4:15:00 PM - 5:30:00 PM (TTr) 

Course Description: :doc:`comp381`

COMP381-002: Bioinfomatics
~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor:  Heather Wheeler

Location: LSC

Schedule: 4:15:00 PM - 6:45:00 PM (W) 

Course Description: :doc:`comp381`

COMP388-001: RAD.NET
~~~~~~~~~~~~~~~~~~~~

Instructor: Karim Kabani

Location: WTC

Schedule: 10:00:00 AM - 12:30:00 PM (Sa) 

Course Description: :doc:`comp388`

COMP388-002: Machine Learning
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert

Location: LSC

Schedule: 7:00:00 PM - 9:30:00 PM (Tr) 

Course Description: :doc:`comp388`

COMP388-003: Metagenomics
~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti

Location: LSC

Schedule: 4:15:00 PM - 6:45:00 PM (T) 

Course Description: :doc:`comp388`

COMP388-004: Foundations of CS 1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington

Location: WTC

Schedule: 4:15:00 PM - 8:15:00 PM (M) 

Course Description: :doc:`comp388`

Note: This course meets for the first 8 weeks, 
Mondays 4:15-8:15PM, replacing holiday/vacation
Mondays with Fridays 4:15-8:15PM. It also meets 
8 consecutive Wednesdays, 4:15-6:30PM, Aug 26 - Oct 14.  

COMP388-005: Foundations of CS 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal

Location: WTC

Schedule: 4:15:00 PM - 8:15:00 PM (M) 

Course Description: :doc:`comp388`

Note: Comp 388-5 meets Mondays for the last 8 
weeks of the semester, Oct 19 - Dec 7 4:15-8:15PM
and also Wednesdays 4:15-6:30PM, Oct 21 - Dec 9, 
excluding Weds Nov 25, during Thanksgiving vacation.

COMP388-422: Software Development for Wireless/Mobile Devices
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Dima Dligach

Location: LSC

Schedule: 2:45:00 PM - 5:15:00 PM (F) 

Course Description: :doc:`comp388`

COMP388-424: Client-Side Web Design
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas Hayward

Location: WTC

Schedule: 4:15:00 PM - 6:45:00 PM (Tr) 

Course Description: :doc:`comp388`

COMP388-433: Web Services Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Berhane Zewdie

Location: WTC

Schedule: 7:00:00 PM - 9:30:00 PM (T) 

Course Description: :doc:`comp388`

COMP390-01E: Broaden Particip STEM (Computing, Math & Science)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg

Location: LSC

Schedule: 1:40:00 PM - 2:30:00 PM (MW) 

Course Description: :doc:`comp390`

COMP391-01E: Internship in CS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp391`

COMP398-01E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp398`

COMP398-02E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp398`

COMP398-03E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp398`

COMP398-04E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg

Location: LSC

Schedule:  -  () 

Course Description: :doc:`comp398`

COMP398-05E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp398`

COMP398-06E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp398`

COMP398-07E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp398`

COMP398-08E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti

Location: LSC

Schedule:  -  () 

Course Description: :doc:`comp398`

COMP398-09E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp398`

COMP398-10E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp398`

COMP399-001: Computer Science Seminar
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert

Location: LSC

Schedule: 12:35:00 PM - 1:25:00 PM (F) 

Course Description: :doc:`comp399`

.. _fallm_graduate_courses_list:

Graduate Courses
~~~~~~~~~~~~~~~~

COMP410-001: Operating Systems
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Joseph Paul Kaylor

Location: LSC

Schedule: 7:00:00 PM - 9:30:00 PM (M) 

Course Description: :doc:`comp410`

COMP412-001: Free/Open Source Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: George Thiruvathukal

Location: ONLN

Schedule:  -  () 

Course Description: :doc:`comp412`

COMP413-001: Intermediate Object-Oriented Development
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis

Location: WTC

Schedule: 4:15:00 PM - 6:45:00 PM (T) 

Course Description: :doc:`comp413`

COMP417-001: Social and Ethical Issues in Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Roxanne Schwab

Location: **LSC**

Schedule: 4:15:00 PM - 6:45:00 PM (W) 

Course Description: :doc:`comp417`

COMP420-001: Software Systems Analysis

Students needing to get to a 7PM WTC class will be allowed to
leave early.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Conrad Weisert

Location: WTC

Schedule: 4:15:00 PM - 6:45:00 PM (M) 

Course Description: :doc:`comp420`

COMP422-001: Software Development for Wireless/Mobile Devices
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Dima Dligach

Location: LSC

Schedule: 2:45:00 PM - 5:15:00 PM (F) 

Course Description: :doc:`comp422`

COMP424-001: Client-Side Web Design
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas Hayward

Location: WTC

Schedule: 4:15:00 PM - 6:45:00 PM (Tr) 

Course Description: :doc:`comp424`

COMP431-001: Cryptography
~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Stephen Doty

Location: LSC

Schedule: 9:20:00 AM - 10:10:00 AM (MWF) 

Course Description: :doc:`comp431`

COMP433-001: Web Services Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Berhane Zewdie

Location: WTC

Schedule: 7:00:00 PM - 9:30:00 PM (T) 

Course Description: :doc:`comp433`

COMP436-001: Markup Languages
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Matthew William Bone

Location: WTC

Schedule: 7:00:00 PM - 9:30:00 PM (W) 

Course Description: :doc:`comp436`

COMP443-001: Computer Networks
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal

Location: WTC

Schedule: 4:15:00 PM - 6:45:00 PM (T) 

Course Description: :doc:`comp443`

COMP443-002: Computer Networks
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal

Location: ONLN

Schedule:  -  () 

Course Description: :doc:`comp443`

Info: This is an online class that includes
synchronous and asynchronous interaction
among students and instructor. Participation
in synchronous sessions is strongly recommended.

COMP447-001: Intrusion Detection and Computer Forensics
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz

Location: WTC

Schedule: 5:45:00 PM - 8:15:00 PM (F) 

Course Description: :doc:`comp447`

COMP447-002: Intrusion Detection and Computer Forensics
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz

Location: ONLN

Schedule:  -  () 

Course Description: :doc:`comp447`

Note: This is an online class. The classroom session will be broadcast live on
Friday evenings via AdobeConnect allowing online student interaction.  Sessions
will also be recorded and made available. Students may participate
synchronously or asynchronously at their discretion.

COMP453-001: Database Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman

Location: WTC

Schedule: 7:00:00 PM - 9:30:00 PM (Tr) 

Course Description: :doc:`comp453`

COMP453-002: Database Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman

Location: ONLN

Schedule:  -  () 

Course Description: :doc:`comp453`

Note:  This is an online class.  All lectures will be recorded. 
Students may be asked to attend smaller-group online interactive 
discussions during the semester.

COMP464-001: High-Performance Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Sharan Kalwani

Location: WTC

Schedule: 7:00:00 PM - 9:30:00 PM (W) 

Course Description: :doc:`comp464`

COMP488-001: RAD.NET
~~~~~~~~~~~~~~~~~~~~

Instructor: Karim Kabani

Location: WTC

Schedule: 10:00:00 AM - 12:30:00 PM (Sa) 

Course Description: :doc:`comp488`

COMP488-002: Machine Learning
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert

Location: LSC

Schedule: 7:00:00 PM - 9:30:00 PM (Tr) 

Course Description: :doc:`comp488`

COMP488-003: Metagenomics
~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti

Location: LSC

Schedule: 4:15:00 PM - 6:45:00 PM (T) 

Course Description: :doc:`comp488`

COMP488-381: Bioinfomatics
~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor:  Heather Wheeler

Location: LSC

Schedule: 4:15:00 PM - 5:30:00 PM (TTr) 

Course Description: :doc:`comp488`

COMP488-382: Bioinfomatics
~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor:  Heather Wheeler

Location: LSC

Schedule: 4:15:00 PM - 6:45:00 PM (W) 

Course Description: :doc:`comp488`

COMP490-001: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp490`

COMP490-002: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp490`

COMP490-003: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp490`

COMP490-004: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp490`

COMP490-005: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp490`

COMP490-006: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp490`

COMP490-007: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp490`

COMP490-008: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp490`

COMP490-009: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp490`

COMP490-010: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp490`


COMP499-001: Internship
~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp499`

COMP499-002: Internship
~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp499`

COMP605-001: Master of Science Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington

Location: WTC

Schedule:  -  () 

Course Description: :doc:`comp605`

.. _fallm_csis_courses_list:

CSIS Courses
~~~~~~~~~~~~

CSIS494-001: Data Mining
~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mary Malliaris (ISOM faculty)

Location: WTC

Schedule: 6-9PM, M - quarter course INFS 494

Course Description: :doc:`csis494`

Any CSIS courses will not open for our students until at least after 
August 2 and possibly never if the course fills with 
Business School students first and stays full.  

