Widescreen/Table Format - Fall 2015 - Schedule
=============================================================
The following courses will (tentatively) be held during the Fall 2015 semester.

For classroom locations and open/full status, see `LOCUS <http://www.luc.edu/locus>`_.

Note: While we update this page regularly, please check 
`LOCUS <http://www.luc.edu/locus>`_ for the most recent information.

**In case of conflict, information on LOCUS should be considered authoritative.**

QuickLinks
~~~~~~~~~~

* :doc:`fallmobile`
* :ref:`undergraduate_courses_table`
* :ref:`graduate_courses_table`
* :ref:`csis_courses_table`
.. _undergraduate_courses_table:

Undergraduate Courses
~~~~~~~~~~~~~~~~~~~~~

:doc:`comp111`
-------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   01W, George Thiruvathukal, 12:35:00 PM - 1:25:00 PM, MWF, LSC, N/A

:doc:`comp125`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Channah Naiman, 1:00:00 PM - 2:15:00 PM, TTr, LSC, N/A
   002, Channah Naiman, 4:15:00 PM - 6:45:00 PM, T, LSC, N/A

:doc:`comp150`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Robin (CS hire) Milner, 2:45:00 PM - 4:00:00 PM, MW, LSC, N/A
   002, Chandra N Sekharan, 11:30:00 AM - 12:45:00 PM, TTr, LSC, N/A
   003, Grace (PT) Hopper, 12:35:00 PM - 1:25:00 PM, MWF, LSC, N/A

:doc:`comp163`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Ronald I Greenberg, 11:30:00 AM - 12:20:00 PM, MWF, LSC, N/A
   002, Curtis D Tuckey, 4:15:00 PM - 5:30:00 PM, MW, LSC, N/A
   003, Curtis D Tuckey, 6:00:00 PM - 7:15:00 PM, MW, LSC, N/A

:doc:`comp170`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Robert Yacobellis, 10:00:00 AM - 11:15:00 AM, TTr, LSC, N/A
   002, Robert Yacobellis, 1:00:00 PM - 2:15:00 PM, TTr, LSC, N/A
   003, William Honig, 2:30:00 PM - 3:45:00 PM, TTr, LSC, N/A
   004, William Honig, 4:15:00 PM - 6:45:00 PM, T, LSC, N/A
   01L, Robert Yacobellis, 11:15:00 AM - 11:40:00 AM, TTr, LSC, N/A
   02L, Robert Yacobellis, 12:35:00 PM - 1:00:00 PM, TTr, LSC, N/A
   03L, William Honig, 3:45:00 PM - 4:05:00 PM, TTr, LSC, N/A
   04L, William Honig, 7:00:00 PM - 7:50:00 PM, T, LSC, N/A

:doc:`comp215`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Christine A Haught, 2:30:00 PM - 3:45:00 PM, TTr, LSC, N/A

:doc:`comp250`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   01W, Roxanne Schwab, 2:45:00 PM - 4:00:00 PM, MW, LSC, N/A

:doc:`comp251`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Guy Bevente, 7:00:00 PM - 9:30:00 PM, M, LSC, N/A

:doc:`comp264`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Ronald I Greenberg, 10:25:00 AM - 11:15:00 AM, MWF, LSC, N/A

:doc:`comp271`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Chandra N Sekharan, 2:30:00 PM - 3:45:00 PM, TTr, LSC, N/A
   002, Maria Del Carmen Saenz, 6:00:00 PM - 8:30:00 PM, Tr, LSC, N/A
   01L, Chandra N Sekharan, 3:45:00 PM - 4:05:00 PM, TTr, LSC, N/A
   02L, Maria Del Carmen Saenz, 8:30:00 PM - 9:20:00 PM, Tr, LSC, N/A

:doc:`comp312`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   01E, George Thiruvathukal,  - , , ONLN, N/A

:doc:`comp313`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Konstantin Laufer, 2:45:00 PM - 5:15:00 PM, W, LSC, N/A

:doc:`comp314`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Andrew N Harrington, 3:00:00 PM - 4:00:00 PM, M, WTC, N/A

:doc:`comp315`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Andrew N Harrington, 3:00:00 PM - 4:00:00 PM, M, WTC, N/A

:doc:`comp317`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   01W, Matthew Paul Butcher, 7:00:00 PM - 9:30:00 PM, T, LSC, N/A

:doc:`comp320`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Conrad Weisert, 4:15:00 PM - 6:45:00 PM, M, WTC, N/A

:doc:`comp331`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Stephen Doty, 9:20:00 AM - 10:10:00 AM, MWF, LSC, N/A

:doc:`comp336`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Matthew William Bone, 7:00:00 PM - 9:30:00 PM, W, WTC, N/A

:doc:`comp343`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Peter L Dordal, 4:15:00 PM - 6:45:00 PM, T, WTC, N/A
   002, Peter L Dordal,  - , , ONLN, N/A

:doc:`comp347`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Corby Schmitz, 5:45:00 PM - 8:15:00 PM, F, WTC, N/A
   002, Corby Schmitz,  - , , ONLN, N/A

:doc:`comp363`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Mark Albert, 2:45:00 PM - 5:15:00 PM, M, LSC, N/A

:doc:`comp364`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Sharan Kalwani, 7:00:00 PM - 9:30:00 PM, W, WTC, N/A

:doc:`comp374`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Joseph Paul Kaylor, 7:00:00 PM - 9:30:00 PM, M, LSC, N/A

:doc:`comp381`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001,  Louis (new BIOI hire) Pasteur, 4:15:00 PM - 5:30:00 PM, TTr, LSC, N/A
   002,  Louis (new BIOI hire) Pasteur, 4:15:00 PM - 6:45:00 PM, W, LSC, N/A

:doc:`comp388`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Karim Kabani, 10:00:00 AM - 12:30:00 PM, Sa, WTC, N/A
   002, Mark Albert, 7:00:00 PM - 9:30:00 PM, Tr, LSC, N/A
   003, Catherine Putonti, 4:15:00 PM - 6:45:00 PM, T, LSC, N/A
   004, Andrew N Harrington, 4:15:00 PM - 8:15:00 PM, M, WTC, N/A
   004, Andrew N Harrington, 4:15:00 PM - 6:45:00 PM, W, WTC, N/A
   005, Peter L Dordal, 4:15:00 PM - 8:15:00 PM, M, WTC, N/A
   005, Peter L Dordal, 4:15:00 PM - 6:45:00 PM, W, WTC, N/A
   422, Robin (CS hire) Milner, 2:45:00 PM - 5:15:00 PM, F, LSC, N/A
   424, Nicholas Hayward, 4:15:00 PM - 6:45:00 PM, Tr, WTC, N/A
   433, Berhane Zewdie, 7:00:00 PM - 9:30:00 PM, T, WTC, N/A

:doc:`comp390`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   01E, Ronald I Greenberg, 1:40:00 PM - 2:30:00 PM, MW, LSC, N/A

:doc:`comp391`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   01E, Robert Yacobellis,  - , , WTC, N/A

:doc:`comp398`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   01E, Konstantin Laufer,  - , , WTC, N/A
   02E, Mark Albert,  - , , WTC, N/A
   03E, Peter L Dordal,  - , , WTC, N/A
   04E, Ronald I Greenberg,  - , , LSC, N/A
   05E, Andrew N Harrington,  - , , WTC, N/A
   06E, William Honig,  - , , WTC, N/A
   07E, Channah Naiman,  - , , WTC, N/A
   08E, Catherine Putonti,  - , , LSC, N/A
   09E, Chandra N Sekharan,  - , , WTC, N/A
   10E, Robert Yacobellis,  - , , WTC, N/A

:doc:`comp399`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Mark Albert, 12:35:00 PM - 1:25:00 PM, F, LSC, N/A

Graduate Courses
~~~~~~~~~~~~~~~~

:doc:`comp410`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Joseph Paul Kaylor, 7:00:00 PM - 9:30:00 PM, M, LSC, N/A

:doc:`comp412`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, George Thiruvathukal,  - , , ONLN, N/A

:doc:`comp413`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Robert Yacobellis, 4:15:00 PM - 6:45:00 PM, T, WTC, N/A

:doc:`comp417`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Roxanne Schwab, 4:15:00 PM - 6:45:00 PM, W, WTC, N/A

:doc:`comp420`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Conrad Weisert, 4:15:00 PM - 6:45:00 PM, M, WTC, N/A

:doc:`comp422`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Robin (CS hire) Milner, 2:45:00 PM - 5:15:00 PM, F, LSC, N/A

:doc:`comp424`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Nicholas Hayward, 4:15:00 PM - 6:45:00 PM, Tr, WTC, N/A

:doc:`comp431`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Stephen Doty, 9:20:00 AM - 10:10:00 AM, MWF, LSC, N/A

:doc:`comp433`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Berhane Zewdie, 7:00:00 PM - 9:30:00 PM, T, WTC, N/A

:doc:`comp436`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Matthew William Bone, 7:00:00 PM - 9:30:00 PM, W, WTC, N/A

:doc:`comp443`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Peter L Dordal, 4:15:00 PM - 6:45:00 PM, T, WTC, N/A
   002, Peter L Dordal,  - , , ONLN, N/A

:doc:`comp447`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Corby Schmitz, 5:45:00 PM - 8:15:00 PM, F, WTC, N/A
   002, Corby Schmitz,  - , , ONLN, N/A

:doc:`comp453`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Channah Naiman, 7:00:00 PM - 9:30:00 PM, Tr, WTC, N/A
   002, Channah Naiman,  - , , ONLN, N/A

:doc:`comp464`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Sharan Kalwani, 7:00:00 PM - 9:30:00 PM, W, WTC, N/A

:doc:`comp488`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Karim Kabani, 10:00:00 AM - 12:30:00 PM, Sa, WTC, N/A
   002, Mark Albert, 7:00:00 PM - 9:30:00 PM, Tr, LSC, N/A
   003, Catherine Putonti, 4:15:00 PM - 6:45:00 PM, T, LSC, N/A
   381,  Louis (new BIOI hire) Pasteur, 4:15:00 PM - 5:30:00 PM, TTr, LSC, N/A
   382,  Louis (new BIOI hire) Pasteur, 4:15:00 PM - 6:45:00 PM, W, LSC, N/A

:doc:`comp490`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Konstantin Laufer,  - , , WTC, N/A
   002, Mark Albert,  - , , WTC, N/A
   003, Peter L Dordal,  - , , WTC, N/A
   004, Ronald I Greenberg,  - , , WTC, N/A
   005, Andrew N Harrington,  - , , WTC, N/A
   006, William Honig,  - , , WTC, N/A
   007, Channah Naiman,  - , , WTC, N/A
   008, Catherine Putonti,  - , , WTC, N/A
   009, Chandra N Sekharan,  - , , WTC, N/A
   010, Robert Yacobellis,  - , , WTC, N/A

:doc:`csis494`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Adam (ISOM faculty) Smith, TBD/ISOM - TBD/ISOM, TBD/ISOM, WTC, N/A

:doc:`comp499`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Andrew N Harrington,  - , , WTC, N/A
   002, Andrew N Harrington,  - , , WTC, N/A

:doc:`comp605`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Andrew N Harrington,  - , , WTC, N/A
