Fall 2015 Schedule (Widescreen/Table Format)
=============================================================
The following courses will (tentatively) be held during the Fall 2015 semester.

For classroom locations and open/full status, see `LOCUS <http://www.luc.edu/locus>`_.

Note: While we update this page regularly, please check 
`LOCUS <http://www.luc.edu/locus>`_ for the most recent information.

**In case of conflict, information on LOCUS should be considered authoritative.**

See `Textbook Information <https://docs.google.com/spreadsheets/d/1EecgbxCW0efku2_yaGrhOEwznoj9eGTJI01dOJgQ1R8/edit#gid=0>`_.

Alternate Mobile format page: :doc:`fallmobile`.

Headings in this Page
~~~~~~~~~~~~~~~~~~~~~~~~~~

* :ref:`fallw_undergraduate_courses`
* :ref:`fallw_graduate_courses`
* :ref:`fallw_csis_courses`

.. _fallw_undergraduate_courses:

Undergraduate Courses
~~~~~~~~~~~~~~~~~~~~~

:doc:`comp111`
-------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   01W, George Thiruvathukal, 12:35:00 PM - 1:25:00 PM, MWF, LSC, N/A

:doc:`comp125`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Channah Naiman, 1:00:00 PM - 2:15:00 PM, TTr, LSC, N/A
   002, Channah Naiman, 4:15:00 PM - 6:45:00 PM, T, LSC, Tentative: May not be offered

:doc:`comp150`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Dima Dligach, 2:45:00 PM - 4:00:00 PM, MW, LSC, N/A
   002, Chandra N Sekharan, 11:30:00 AM - 12:45:00 PM, TTr, LSC, N/A
   003, Grace (PT) Hopper, 12:35:00 PM - 1:25:00 PM, MWF, LSC, N/A

:doc:`comp163`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Ronald I Greenberg, 11:30:00 AM - 12:20:00 PM, MWF, LSC, N/A
   002, Ada (PT) Lovelace, 4:15:00 PM - 5:30:00 PM, MW, LSC, N/A
   003, Ada (PT) Lovelace, 6:00:00 PM - 7:15:00 PM, MW, LSC, N/A

:doc:`comp170`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Robert Yacobellis, 10:00:00 AM - 11:15:00 AM, TTr, LSC, N/A
   002, Robert Yacobellis, 1:00:00 PM - 2:15:00 PM, TTr, LSC, N/A
   003, William Honig, 2:30:00 PM - 3:45:00 PM, TTr, LSC, N/A
   004, William Honig, 4:15:00 PM - 6:45:00 PM, T, LSC, N/A
   01L, Robert Yacobellis, 11:15:00 AM - 11:40:00 AM, TTr, LSC, N/A
   02L, Robert Yacobellis, 12:35:00 PM - 1:00:00 PM, TTr, LSC, N/A
   03L, William Honig, 3:45:00 PM - 4:05:00 PM, TTr, LSC, N/A
   04L, William Honig, 7:00:00 PM - 7:50:00 PM, T, LSC, N/A

:doc:`comp215`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Christine A Haught, 2:30:00 PM - 3:45:00 PM, TTr, LSC, N/A

:doc:`comp250`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   01W, Roxanne Schwab, 2:45:00 PM - 4:00:00 PM, MW, LSC, N/A

:doc:`comp251`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Guy Bevente, 7:00:00 PM - 9:30:00 PM, M, LSC, N/A

:doc:`comp264`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Ronald I Greenberg, 10:25:00 AM - 11:15:00 AM, MWF, LSC, N/A

:doc:`comp271`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Chandra N Sekharan, 2:30:00 PM - 3:45:00 PM, TTr, WTC, N/A
   002, Maria Del Carmen Saenz, 6:00:00 PM - 8:30:00 PM, Tr, LSC, N/A
   01L, Chandra N Sekharan, 3:45:00 PM - 4:05:00 PM, TTr, WTC, N/A
   02L, Maria Del Carmen Saenz, 8:30:00 PM - 9:20:00 PM, Tr, LSC, N/A

:doc:`comp312`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note" 
  :widths: 10, 50, 75, 30, 50, 175

   01E, George Thiruvathukal,  - , , ONLN, This is an online class that includes synchronous and asynchronous interaction among students and Instructor. All sessions will be recorded. Specific synchronous meetings will be scheduled in consultation with students

:doc:`comp313`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Konstantin Laufer, 2:45:00 PM - 5:15:00 PM, W, LSC, N/A

:doc:`comp314-315`
--------------------------

.. was not working?
   replaced
   .. _Programming Team: http://anh.cs.luc.edu/314-315/prog-team.html

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 50, 75, 30, 50, 175

  001, Andrew N Harrington, See Note, TBD, TBD, One organizational meeting Monday August 24 3-4PM in LT 410 to agree on 5 weekend practice times through the end of October. See the `Programming Team <http://anh.cs.luc.edu/314-315/prog-team.html>`_.

:doc:`comp317`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Matthew Paul Butcher, 7:00:00 PM - 9:30:00 PM, T, LSC, N/A

:doc:`comp320`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Conrad Weisert, 4:15:00 PM - 6:45:00 PM, M, WTC, N/A

:doc:`comp331`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Stephen Doty, 9:20:00 AM - 10:10:00 AM, MWF, LSC, N/A

:doc:`comp336`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Matthew William Bone, 7:00:00 PM - 9:30:00 PM, W, WTC, N/A

:doc:`comp343`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 50, 75, 30, 50, 175

   001, Peter L Dordal, 4:15:00 PM - 6:45:00 PM, T, WTC, N/A
   002, Peter L Dordal,  - , , ONLN, This is an online class that includes synchronous and asynchronous interaction among students and instructor. Participation in synchronous sessions is strongly recommended.

:doc:`comp347`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 50, 75, 30, 50, 175

   001, Corby Schmitz, 5:45:00 PM - 8:15:00 PM, F, WTC, N/A
   002, Corby Schmitz,  - , , ONLN, This is an online class. The classroom session will be broadcast live on Friday evenings via AdobeConnect allowing online student interaction.  Sessions will also be recorded and made available. Students may participate synchronously or asynchronously at their discretion.
   
:doc:`comp363`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Mark Albert, 2:45:00 PM - 5:15:00 PM, M, LSC, N/A

:doc:`comp364`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Sharan Kalwani, 7:00:00 PM - 9:30:00 PM, W, WTC, N/A

:doc:`comp374`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Joseph Paul Kaylor, 7:00:00 PM - 9:30:00 PM, M, LSC, N/A

:doc:`comp381`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001,  Heather Wheeler, 4:15:00 PM - 5:30:00 PM, TTr, LSC, N/A
   002,  Heather Wheeler, 4:15:00 PM - 6:45:00 PM, W, LSC, N/A

:doc:`comp388`
--------------------------

Each section is a totally different course.  The course title is in the Note column.

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 50, 75, 30, 50, 175

   001, Karim Kabani, 10:00:00 AM - 12:30:00 PM, Sa, WTC, RAD.net
   002, Mark Albert, 7:00:00 PM - 9:30:00 PM, Tr, LSC, Machine Learning
   003, Catherine Putonti, 4:15:00 PM - 6:45:00 PM, T, LSC, Metagenomics
   004, Andrew N Harrington, See Note, M/Th, WTC, Foundations of CS I: compressed version of Comp 170 meets for the first eight weeks of the Semester Mondays (4:15 PM - 8:15 PM) replacing holiday/vacation Mondays with Fridays (4:15 PM - 8:15 PM).  So the Monday/Friday class schedule is:  Mon Aug 24; Mon Aug 31; Fri Sep 11; Mon Sep 14; Mon Sept 21; Monday Sept 28; Fri Oct 9; Mon Oct 12.  It also meets eight consecutive Thursdays: 4:15 PM - 6:30 PM Aug 27 - Oct 15.  
   005, Peter L Dordal, See Note, M/Th, WTC, Foundations of CS II: compressed version of Comp 271 meets for the last 8 weeks of the semester Mondays Oct 19-Dec 7 (4:15-8:15PM) and also Thursdays Oct 22 - Dec 10 (4:15-6:30PM) excluding Thursday Nov 26 (Thanksgiving).
   422, Dima Dligach , 2:45:00 PM - 5:15:00 PM, F, LSC, Software Development for Wireless/Mobile Devices
   424, Nicholas Hayward, 4:15:00 PM - 6:45:00 PM, Tr, WTC, Client-Side Web Design
   433, Berhane Zewdie, 7:00:00 PM - 9:30:00 PM, T, WTC, Web Services Programming

:doc:`comp390`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   01E, Ronald I Greenberg, 1:40:00 PM - 2:30:00 PM, MW, LSC, N/A

:doc:`comp391`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   01E, Robert Yacobellis,  - , , WTC, N/A

:doc:`comp398`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   01E, Konstantin Laufer,  - , , WTC, N/A
   02E, Mark Albert,  - , , WTC, N/A
   03E, Peter L Dordal,  - , , WTC, N/A
   04E, Ronald I Greenberg,  - , , LSC, N/A
   05E, Andrew N Harrington,  - , , WTC, N/A
   06E, William Honig,  - , , WTC, N/A
   07E, Channah Naiman,  - , , WTC, N/A
   08E, Catherine Putonti,  - , , LSC, N/A
   09E, Chandra N Sekharan,  - , , WTC, N/A
   10E, Robert Yacobellis,  - , , WTC, N/A

:doc:`comp399`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Mark Albert, 12:35:00 PM - 1:25:00 PM, F, LSC, N/A

.. _fallw_graduate_courses:

Graduate Courses
~~~~~~~~~~~~~~~~

:doc:`comp410`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Joseph Paul Kaylor, 7:00:00 PM - 9:30:00 PM, M, LSC, N/A

:doc:`comp412`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 50, 75, 30, 50, 175

   001, George Thiruvathukal,  - , , ONLN, This is an online class that includes synchronous and asynchronous interaction among students and Instructor. All sessions will be recorded. Specific synchronous meetings will be scheduled in consultation with students

:doc:`comp413`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Robert Yacobellis, 4:15:00 PM - 6:45:00 PM, T, WTC, N/A

:doc:`comp417`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Roxanne Schwab, 4:15:00 PM - 6:45:00 PM, W, **LSC**, Students needing to get to a 7PM WTC class will be allowed to leave early.


:doc:`comp420`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Conrad Weisert, 4:15:00 PM - 6:45:00 PM, M, WTC, N/A

:doc:`comp422`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Dima Dligach, 2:45:00 PM - 5:15:00 PM, F, LSC, N/A

:doc:`comp424`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Nicholas Hayward, 4:15:00 PM - 6:45:00 PM, Tr, WTC, N/A

:doc:`comp431`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Stephen Doty, 9:20:00 AM - 10:10:00 AM, MWF, LSC, N/A

:doc:`comp433`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Berhane Zewdie, 7:00:00 PM - 9:30:00 PM, T, WTC, N/A

:doc:`comp436`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Matthew William Bone, 7:00:00 PM - 9:30:00 PM, W, WTC, N/A

:doc:`comp443`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 50, 75, 30, 50, 175

   001, Peter L Dordal, 4:15:00 PM - 6:45:00 PM, T, WTC, N/A
   002, Peter L Dordal,  - , , ONLN,  This is an online class that includes synchronous and asynchronous interaction among students and instructor. Participation in synchronous sessions is strongly recommended.


:doc:`comp447`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 50, 75, 30, 50, 175

   001, Corby Schmitz, 5:45:00 PM - 8:15:00 PM, F, WTC, N/A
   002, Corby Schmitz,  - , , ONLN, This is an online class. The classroom session will be broadcast live on Friday evenings via AdobeConnect allowing online student interaction.  Sessions will also be recorded and made available. Students may participate synchronously or asynchronously at their discretion.

:doc:`comp453`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 50, 75, 30, 50, 175

   001, Channah Naiman, 7:00:00 PM - 9:30:00 PM, Tr, WTC, N/A
   002, Channah Naiman,  - , , ONLN, This is an online class.  All lectures will be recorded. Students may be asked to attend smaller-group online interactive discussions during the semester.

:doc:`comp464`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Sharan Kalwani, 7:00:00 PM - 9:30:00 PM, W, WTC, N/A

:doc:`comp488`
--------------------------

Each section is a totally different course.  The course title is in the Note column.

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Karim Kabani, 10:00:00 AM - 12:30:00 PM, Sa, WTC, RAD.NET
   002, Mark Albert, 7:00:00 PM - 9:30:00 PM, Tr, LSC, Machine Learning
   003, Catherine Putonti, 4:15:00 PM - 6:45:00 PM, T, LSC, Metagenomics
   381, Heather Wheeler, 4:15:00 PM - 5:30:00 PM, TTr, LSC, Bioinformatics
   382, Heather Wheeler, 4:15:00 PM - 6:45:00 PM, W, LSC, Bioinformatics

:doc:`comp490`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Konstantin Laufer,  - , , WTC, N/A
   002, Mark Albert,  - , , WTC, N/A
   003, Peter L Dordal,  - , , WTC, N/A
   004, Ronald I Greenberg,  - , , WTC, N/A
   005, Andrew N Harrington,  - , , WTC, N/A
   006, William Honig,  - , , WTC, N/A
   007, Channah Naiman,  - , , WTC, N/A
   008, Catherine Putonti,  - , , WTC, N/A
   009, Chandra N Sekharan,  - , , WTC, N/A
   010, Robert Yacobellis,  - , , WTC, N/A

:doc:`comp499`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 100, 75, 30, 50, 50

   001, Andrew N Harrington,  - , , WTC, N/A
   002, Andrew N Harrington,  - , , WTC, N/A

:doc:`comp605`
--------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 175, 75, 30, 50, 50

   001, Andrew N Harrington,  - , , WTC, N/A

.. _fallw_csis_courses:

CSIS Courses
~~~~~~~~~~~~

:doc:`csis494`  (meets with INFS 494 in fall Quarter)
------------------------------------------------------

.. csv-table::
  :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
  :widths: 10, 50, 75, 30, 50, 175

   001, Mary Malliaris (ISOM faculty), 6-9PM, M, WTC, Any CSIS courses will not open for our students until at least after August 2 and possibly never if the course fills with Business School students first and stays full.
