Spring 2016 Schedule (Mobile/Single Column Format)
==================================================================

The following courses will (tentatively) be held during the Spring 2016 semester.

For classroom locations and open/full status, see `LOCUS <http://www.luc.edu/locus>`_.

Note: While we update this page regularly, please check `LOCUS <http://www.luc.edu/locus>`_ for the most recent information.

**In case of conflict, information on LOCUS should be considered authoritative.**

QuickLinks
~~~~~~~~~~~~~

* :doc:`springwidescreen`
* :ref:`undergraduate_courses_list`
* :ref:`graduate_courses_list`
* :ref:`csis_courses_list`

.. _undergraduate_courses_list:

Undergraduate Courses
~~~~~~~~~~~~~~~~~~~~~~~~~~

COMP 111-01W: History of Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: George Thiruvathukal 

Time: 11:30 AM - 12:20 PM

Day(s): Monday Wednesday Friday 

Campus: Lakeshore

Course Description: :doc:`comp111`

COMP 125-1: Visual Information Processing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: 1:00 PM - 2:15 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp125`

COMP 125-2: Visual Information Processing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Guy Bevente 

Time: 7:00 PM - 9:30 PM

Day(s): Thursday 

Campus: Lakeshore

Course Description: :doc:`comp125`

COMP 150-1: Introduction to Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington 

Time: 2:30 PM - 4:00 PM

Day(s): Tuesday, see note

Campus: Lakeshore

Course Description: :doc:`comp150`

Notes: This class has run successfully both face to face and online, with the same content.  This blended format takes advantage of face-to-face in initially getting to know each other, getting the class going, finding partners, and getting direct help with any online technology.  Later, since the class is flipped, and most all interaction is help on your individual computer work, help can come online, either in part of regular class time or at varied times convenient to you and the instructor.  We will use software to share screens online.  A quiet place is important for online help, with a computer that you have access to having good Internet speed and with the ability to talk and listen online.  

COMP 150-2: Introduction to Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: TBD 

Time: 7:00 PM - 9:30 PM

Day(s): Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp150`

COMP 150-3: Introduction to Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Heather E. Wheeler 

Time: 12:10 PM - 1:25 PM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp150`

COMP 163-1: Discrete Structures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: TBD 

Time: 2:45 PM - 4:00 PM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp163`

COMP 163-2: Discrete Structures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: TBD 

Time: 4:15 PM - 5:30 PM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp163`

COMP 170-1: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: 10:00 AM - 11:15 AM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp170`

COMP 170-2: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Dmitriy Dligach 

Time: 10:25 AM - 11:40 AM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp170`

COMP 170-3: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Maria Del Carmen Saenz 

Time: 6:00 PM - 8:30 PM

Day(s): Tuesday 

Campus: Lakeshore

Course Description: :doc:`comp170`

COMP 170-4: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Dmitriy Dligach 

Time: 12:10 PM - 1:25 PM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp170`

COMP 170-01L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: 11:30 AM - 11:55 AM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp170`

COMP 170-02L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Dmitriy Dligach 

Time: 10:25 AM - 11:15 AM

Day(s): Friday 

Campus: Lakeshore

Course Description: :doc:`comp170`

COMP 170-03L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Maria Del Carmen Saenz 

Time: 8:30 PM - 9:20 PM

Day(s): Tuesday 

Campus: Lakeshore

Course Description: :doc:`comp170`

COMP 170-04L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Dmitriy Dligach 

Time: 12:35 PM - 1:25 PM

Day(s): Friday 

Campus: Lakeshore

Course Description: :doc:`comp170`

COMP 250-01W: Introduction to Scientific and Technical Communication
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Roxanne Schwab 

Time: 2:45 PM - 4:00 PM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp250`

COMP 250-02W: Introduction to Scientific and Technical Communication
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Roxanne Schwab 

Time: 7:00 PM - 9:30 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp250`

COMP 264-1: Introduction to Computer Systems
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg 

Time: 9:20 AM - 10:10 AM

Day(s): Monday Wednesday Friday 

Campus: Lakeshore

Course Description: :doc:`comp264`

COMP 271-1: Data Structures: Algorithms and Applications
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti 

Time: 2:30 PM - 3:45 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp271`

COMP 271-2: Data Structures: Algorithms and Applications
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti 

Time: 4:15 PM - 6:45 PM

Day(s): Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp271`

COMP 271-01L: Data Structures: Algorithms and Applications
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti 

Time: 3:45 PM - 4:05 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp271`

COMP 271-02L: Data Structures: Algorithms and Applications
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti 

Time: 7:00 PM - 7:50 PM

Day(s): Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp271`

COMP 300-1: Data Warehousing and Data Mining
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: 4:15 PM - 6:45 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp300`

COMP 300-2: Data Warehousing and Data Mining
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: See notes

Day(s): See notes 

Campus: Online

Notes: This class is a totally online asynchronous course.  Exams may be synchronous.  Combined with COMP 488-302.

Course Description: :doc:`comp300`

COMP 305-1: Database Administration
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal 

Time: 4:15 PM - 6:45 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp305`

COMP 312-01E: Open Source Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: TBD 

Time: 7:00 PM - 9:30 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp312`

COMP 313-1: Intermediate Object-Oriented Development
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: 1:00 PM - 2:15 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp313`

COMP 317-1: Social, Legal, and Ethical Issues in Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Matthew Paul Butcher 

Time: TBD

Day(s): TBD 

Campus: Online

Notes: This is an online class.  All lectures will be pre-recorded.  Students are asked to attend smaller-group online interactive discussions at regular intervals during the semester with possible times chosen to fit different groups' schedules.

Course Description: :doc:`comp317`

COMP 317-01W: Social, Legal, and Ethical Issues in Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Roxanne Schwab 

Time: 7:00 PM - 9:30 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp317`

COMP 319-1: Introduction to UNIX
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Jose Luis Gahete Diaz 

Time: 1:40 PM - 2:30 PM

Day(s): Friday 

Campus: Lakeshore

Course Description: :doc:`comp319`

COMP 324-1: Client-Side Web Development
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas J Hayward 

Time: 4:15 PM - 6:45 PM

Day(s): Monday 

Campus: Water Tower

Course Description: :doc:`comp324`

COMP 330-1: Software Engineering
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: George Thiruvathukal 

Time: 6:00 PM - 8:30 PM

Day(s): Thursday 

Campus: Lakeshore

Course Description: :doc:`comp330`

COMP 339-1: Distributed Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Sarah Kaylor 

Time: 7:00 PM - 9:30 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp339`

COMP 340-1: Computer Forensics
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Thomas Yarrish 

Time: 7:00 PM - 9:30 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp340`

COMP 341-1: Human-Computer Interaction
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas J Hayward 

Time: 7:00 PM - 9:30 PM

Day(s): Thursday 

Campus: Water Tower

Course Description: :doc:`comp341`

COMP 348-1: Network Security
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz 

Time: 5:30 PM - 8:00 PM

Day(s): Friday 

Campus: Water Tower

Course Description: :doc:`comp348`

COMP 348-2: Network Security
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz 

Time: TBD

Day(s): TBD 

Campus: Online

Notes: This is an online class.  The classroom session will be broadcast live on Friday evenings via AdobeConnect allowing online student interaction.  Sessions will also be recorded and made available.  Students may participate synchronously or asynchronously at their discretion.  Combined with COMP 448-002.

Course Description: :doc:`comp348`

COMP 353-1: Database Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan 

Time: 4:15 PM - 6:45 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp353`

COMP 363-1: Desgn and Analysis Computer Algorithms
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: 2:45 PM - 5:15 PM

Day(s): Thursday 

Campus: Lakeshore

Course Description: :doc:`comp363`

COMP 372-1: Programming Languages
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer 

Time: 2:45 PM - 5:15 PM

Day(s): Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp372`

COMP 373-1: Objects, Frameworks, and Patterns
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Berhane Zewdie 

Time: 7:00 PM - 9:30 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp373`

COMP 377-1: IT Project Management
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Conrad Weisert 

Time: 4:15 PM - 6:45 PM

Day(s): Friday 

Campus: Water Tower

Course Description: :doc:`comp377`

COMP 378-1: Artificial Intelligence
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Conrad Weisert 

Time: 2:45 PM - 5:15 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp378`

COMP 383-1: Computational Biology
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Heather E. Wheeler 

Time: 2:45 PM - 4:05 PM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp383`

COMP 388-4: Foundations of Computer Science I
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**This course meets during the first 8 week session of the semester.**

Instructor: Andrew N Harrington 

Time: See Note

Day(s): See Note 

Campus: Water Tower

Course Description: :doc:`comp388`

Note:  Eight Week-First Session.  This section is restricted to students with undergraduate degrees.  Department Consent required, and then a Computer Science Department staff member will enroll you.  FIRST CLASS EARLY:  Friday before other classes start:  Friday, January 15!  And then on for the next seven weeks, ending before vacation week.  Classes meet from 4:15 pm - 8:15 pm on Fri, Jan 15, and Fri, Jan 22.  And then, 4:15 pm- 8:15 pm for the next 6 Mondays:  Jan 25, Feb 1, Feb 8, Feb 15, Feb 22, Feb 29.  Labs meet on Wednesdays, 4:15 pm - 6:30 pm:  Jan 20, Jan 27, Feb 3, Feb 10, Feb 17, Feb 24, Mar 2.

COMP 388-5: Foundations of Computer Science II
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**This course meets during the second 8 week session of the semester.**

Instructor: Peter L Dordal 

Time: See Note

Day(s): See Note 

Campus: Water Tower

Course Description: :doc:`comp388`

Notes: Eight Week-Second Session.  This section is restricted to students with undergraduate degrees.  Department Consent required, and then a Computer Science Department staff member will enroll you.  Eight weeks after vacation, including two meetings in finals week.  Mondays, 4:15 pm -8:15 pm:  March 14, March 21, March 28, April 4, April 11, April 18, April 25, May 2.  Labs meet on Wednesdays, 4:15 pm - 6:30 pm:  March 16, March 23, March 30, April 6, April 13, April 20, April 27, May 4.

COMP 388-6: Prog Lang and Systems Seminar
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Jose Luis Gahete Diaz 

Time: 2:45 PM - 4:00 PM

Day(s): Friday 

Campus: Lakeshore

Course Description: :doc:`comp388`

COMP 388-7: Physical Design and Fabrication
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: TBD 

Time: 7:00 PM - 9:30 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp388`

COMP 391-01E: Internship in CS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp391`

COMP 397-8: Research Seminar
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: TBD

Day(s): TBD 

Campus: Online

Notes: The Computer Science Seminar course and the Research Seminar course will meet on alternate weeks at the scheduled course time.

Course Description: :doc:`comp397`

COMP 398-01E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-02E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-03E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Dmitriy Dligach 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-04E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-05E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-06E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-07E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas J Hayward 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-08E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-09E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-10E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-11E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-12E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Heather E. Wheeler 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-13E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 399-1: Computer Science Seminar
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: 11:30 AM - 12:45 PM

Day(s): Tuesday 

Campus: Lakeshore

Course Description: :doc:`comp399`

.. _graduate_courses_list:

Graduate Courses
~~~~~~~~~~~~~~~~~~

COMP 412-1: Open Source Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: TBD 

Time: 7:00 PM - 9:30 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp412`

COMP 413-1: Intermediate Object-Oriented Development
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: 4:15 PM - 6:45 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp413`

COMP 417-1: Social and Ethical Issues in Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal 

Time: 4:15 PM - 6:45 PM

Day(s): Thursday 

Campus: Water Tower

Course Description: :doc:`comp417`

COMP 424-1: Client-Side Web Design
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas J Hayward 

Time: 4:15 PM - 6:45 PM

Day(s): Monday 

Campus: Water Tower

Course Description: :doc:`comp424`

COMP 439-1: Distributed Systems
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Sarah Kaylor 

Time: 7:00 PM - 9:30 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp439`

COMP 441-1: Human-Computer Interface Design
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas J Hayward 

Time: 7:00 PM - 9:30 PM

Day(s): Thursday 

Campus: Water Tower

Course Description: :doc:`comp441`

COMP 448-1: Network Security
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz 

Time: 5:30 PM - 8:00 PM

Day(s): Friday 

Campus: Water Tower

Course Description: :doc:`comp448`

COMP 448-2: Network Security
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz 

Time: TBD

Day(s): TBD 

Campus: Online

Notes: This is an online class.  The classroom session will be broadcast live on Friday evenings via AdobeConnect allowing online student interaction.  Sessions will also be recorded and made available.  Students may participate synchronously or asynchronously at their discretion.  Combined with COMP 348-002.

Course Description: :doc:`comp448`

COMP 460-1: Algorithms & Complexity
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan 

Time: 2:45 PM - 5:15 PM

Day(s): Tuesday 

Campus: Lakeshore

Course Description: :doc:`comp460`

COMP 471-1: Thry of Programming Languages
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer 

Time: 2:45 PM - 5:15 PM

Day(s): Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp471`

COMP 473-1: Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Berhane Zewdie 

Time: 7:00 PM - 9:30 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp473`

COMP 474-1: Software Engineering
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: TBD 

Time: 7:00 PM - 9:30 PM

Day(s): Thursday 

Campus: Water Tower

Course Description: :doc:`comp474`

COMP 477-1: IT Project Management
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Conrad Weisert 

Time: 4:15 PM - 6:45 PM

Day(s): Friday 

Campus: Water Tower

Course Description: :doc:`comp477`

COMP 484-1: Artificial Intelligence
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Conrad Weisert 

Time: 2:45 PM - 5:15 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp484`

COMP 488-7: Physical Design and Fabrication
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: TBD 

Time: 7:00 PM - 9:30 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp488`

COMP 488-301: Data Warehousing and Data Mining
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: 4:15 PM - 6:45 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp488`

COMP 488-302: Data Warehousing and Data Mining
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: See notes

Day(s): See notes 

Campus: Online

Notes: This class is a totally online asynchronous course.  Exams may be synchronous.  Combined with COMP 300-002.

Course Description: :doc:`comp488`

COMP 488-305: Database Administration
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal 

Time: 4:15 PM - 6:45 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp488`

COMP 488-340: Computer Forensics
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Thomas Yarrish 

Time: 7:00 PM - 9:30 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp488`

COMP 488-383: Computational Biology
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Heather E. Wheeler 

Time: 2:45 PM - 4:05 PM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp488`

COMP 488-402: Intro Digital Humanities Design & Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas J Hayward 

Time: 4:15 PM - 6:45 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp488`

COMP 490-1: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-2: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-3: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Dmitriy Dligach 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-4: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-5: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-6: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-7: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas J Hayward 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-8: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-9: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-10: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-11: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-12: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Heather E. Wheeler 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-13: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 499-1: Internship
~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp499`

COMP 605-1: Master of Science Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp605`

.. _csis_courses_list:

CSIS Courses
~~~~~~~~~~~~~~~~~~

No CSIS Courses Currently Available.