.. _csis_courses_table:

CSIS Courses
~~~~~~~~~~~~~~~

:doc:`csis794`
---------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 75, 75, 30, 50, 50

    1, Serhat Cicekoglu, 6:00 PM - 9:00 PM, M, Water Tower, [#]_

.. rubric:: Notes

.. [#] Meeting Dates: 02/19/2015 - 05/09/2015

:doc:`csis796`
---------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 75, 75, 30, 50, 50

    1, Abhishek Sharma, 6:00 PM - 9:00 PM, M, Water Tower, [#]_

.. rubric:: Notes

.. [#] Meeting Dates: 02/19/2015 - 05/09/2015
