Spring 2015 Schedule (Mobile/Single Column Format)
==================================================================

The following courses will (tentatively) be held during the Spring 2015 semester.

For classroom locations and open/full status, see `LOCUS <http://www.luc.edu/locus>`_.

Note: While we update this page regularly, please check `LOCUS <http://www.luc.edu/locus>`_ for the most recent information.

**In case of conflict, information on LOCUS should be considered authoritative.**

See `Textbook Information <https://docs.google.com/spreadsheet/ccc?key=0Aj_4VraMwHUodEdONlp1UW1tX203cURYV2dwQWl2VUE&usp=drive_web#gid=0>`_.

QuickLinks
~~~~~~~~~~~~~

* :doc:`springwidescreen`
* :ref:`undergraduate_courses_list`
* :ref:`graduate_courses_list`
* :ref:`csis_courses_list`

.. _undergraduate_courses_list:

Undergraduate Courses
~~~~~~~~~~~~~~~~~~~~~~~~~~

COMP 125-1: Visual Information Processing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: 1:00 PM - 2:15 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp125`

COMP 125-2: Visual Information Processing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: 4:15 PM - 6:45 PM

Day(s): Thursday 

Campus: Lakeshore

Course Description: :doc:`comp125`

COMP 150-1: Introduction to Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Zachary Romer 

Time: 2:30 PM - 3:45 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp150`

COMP 150-2: Introduction to Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Zachary Romer 

Time: 11:30 AM - 12:45 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp150`

COMP 150-3: Introduction to Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Curtis D Tuckey 

Time: 12:10 PM - 1:25 PM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp150`

COMP 163-2: Discrete Structures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Curtis D Tuckey 

Time: 4:15 PM - 5:30 PM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp163`

COMP 170-1: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: 10:00 AM - 11:15 AM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Notes: Enrolling in this course will also enroll you in its lab section (01L). Meeting time is effectively 10:00 AM - 11:55 AM.

Course Description: :doc:`comp170`

COMP 170-2: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington 

Time: 1:00 PM - 2:15 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Notes: Enrolling in this course will also enroll you in its lab section (02L). Meeting time is effectively 12:20 PM - 2:15 PM.


Course Description: :doc:`comp170`

COMP 170-3: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: 4:15 PM - 6:45 PM

Day(s): Tuesday 

Campus: Lakeshore

Notes: Enrolling in this course will also enroll you in its lab section (03L). Meeting time is effectively 4:15 PM - 7:45 PM.


Course Description: :doc:`comp170`

COMP 170-4: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: George Thiruvathukal 

Time: 10:25 AM - 11:15 AM

Day(s): Monday Wednesday Friday 

Campus: Lakeshore

Notes: Enrolling in this course will also enroll you in its lab section (04L). Meeting time is effectively 10:25 AM - 11:55 AM, except on Fridays when it is 10:25 AM - 11:15 AM.


Course Description: :doc:`comp170`

COMP 170-01L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: 11:30 AM - 11:55 AM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Notes: This is the lab section for 170-001.

Course Description: :doc:`comp170`

COMP 170-02L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington 

Time: 12:20 PM - 12:45 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Notes: This is the lab section for 170-002.

Course Description: :doc:`comp170`

COMP 170-03L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: 7:00 PM - 7:45 PM

Day(s): Tuesday 

Campus: Lakeshore

Notes: This is the lab section for 170-003.

Course Description: :doc:`comp170`

COMP 170-04L: Introduction to Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: George Thiruvathukal 

Time: 11:30 AM - 11:55 AM

Day(s): Monday Wednesday 

Campus: Lakeshore

Notes: This is the lab section for 170-004.

Course Description: :doc:`comp170`

COMP 250-01W: Introduction to Scientific and Technical Communication
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Roxanne Schwab 

Time: 2:45 PM - 4:00 PM

Day(s): Monday Wednesday 

Campus: Lakeshore

Course Description: :doc:`comp250`

COMP 250-02W: Introduction to Scientific and Technical Communication
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Roxanne Schwab 

Time: 7:00 PM - 9:30 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp250`

COMP 251-1: Introduction to Database Systems
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Guy Bevente 

Time: 7:00 PM - 9:30 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp251`

COMP 264-1: Introduction to Computer Systems
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg 

Time: 4:15 PM - 6:45 PM

Day(s): Thursday 

Campus: Lakeshore

Course Description: :doc:`comp264`

COMP 271-1: Data Structures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Maria Saenz 

Time: 7:00 PM - 8:15 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Notes: Enrolling in this course will also enroll you in its lab section (01L). Meeting time is effectively 7:00 PM - 8:55 PM.

Course Description: :doc:`comp271`

COMP 271-2: Data Structures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti 

Time: 4:15 PM - 6:45 PM

Day(s): Wednesday 

Campus: Lakeshore

Notes: Enrolling in this course will also enroll you in its lab section (02L). Meeting time is effectively 4:15 PM - 7:50 PM.

Course Description: :doc:`comp271`

COMP 271-01L: Data Structures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Maria Saenz 

Time: 8:30 PM - 8:55 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Notes: This is the lab section for 271-001.

Course Description: :doc:`comp271`

COMP 271-02L: Data Structures
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti 

Time: 7:00 PM - 7:50 PM

Day(s): Wednesday 

Campus: Lakeshore

Notes: This is the lab section for 271-002.

Course Description: :doc:`comp271`

COMP 300-1: Data Warehousing and Data Mining
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: 4:15 PM - 6:45 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp300`

COMP 305-1: Database Administration
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal 

Time: 4:15 PM - 6:45 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp305`

COMP 312-01E: Free/Open Source Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Sharan Kalwani 

Time: 7:00 PM - 9:30 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp312`

COMP 313-1: Intermediate Object-Oriented Development
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: 2:30 PM - 3:45 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp313`

COMP 317-1: Social, Legal, and Ethical Issues in Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Matthew Paul Butcher 

Time: TBD

Day(s): TBD 

Campus: Online

Notes: This is an online class.  All lectures will be pre-recorded. Students are asked to attend smaller-group online interactive discussions at regular intervals during the semester, with possible times chosen to fit different groups' schedules.

Course Description: :doc:`comp317`

COMP 330-1: Software Engineering
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig 

Time: 4:15 PM - 6:45 PM

Day(s): Tuesday 

Campus: Lakeshore

Course Description: :doc:`comp330`

COMP 340-1: Computer Forensics
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Thomas Yarrish 

Time: 7:00 PM - 9:30 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp340`

COMP 348-1: Network Security
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz 

Time: 5:30 PM - 8:00 PM

Day(s): Friday 

Campus: Water Tower

Course Description: :doc:`comp348`

COMP 348-2: Network Security
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz 

Time: TBD

Day(s): TBD 

Campus: Online

Course Description: :doc:`comp348`

COMP 353-1: Database Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan 

Time: 4:15 PM - 6:45 PM

Day(s): Monday 

Campus: Lakeshore

Course Description: :doc:`comp353`

COMP 366-1: Microcomputer Design and Interfacing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig 

Time: 1:00 PM - 2:15 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp366`

COMP 372-1: Programming Languages
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer 

Time: 4:15 PM - 6:45 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp372`

COMP 373-1: Objects, Frameworks, and Patterns
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Berhane Zewdie 

Time: 7:00 PM - 9:30 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp373`

COMP 378-1: Artificial Intelligence
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Conrad Weisert 

Time: 7:00 PM - 9:30 PM

Day(s): Monday 

Campus: Water Tower

Course Description: :doc:`comp378`

COMP 388-1: Human-Computer Interface Design
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas Hayward 

Time: 7:00 PM - 9:30 PM

Day(s): Thursday 

Campus: Water Tower

Course Description: :doc:`comp388`

COMP 388-2: Advanced Algorithms & Complexity
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan 

Time: 4:15 PM - 6:45 PM

Day(s): Tuesday 

Campus: Water Tower

Notes: prerequisite: COMP 363

Course Description: :doc:`comp388`

COMP 388-3: IT Project Management
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Conrad Weisert 

Time: 4:15 PM - 6:45 PM

Day(s): Friday 

Campus: Water Tower

Course Description: :doc:`comp388`

COMP 388-4: Foundations of Comp Sci I
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**This course meets during the first 8 week session of the semester.**

Instructor: Andrew N Harrington 

Time: See Note

Day(s): See Note 

Campus: Water Tower

Notes: Time and Days: Seven weeks from start of semester, ending before vacation week. Classes 5:30-9:30PM all Mondays except MLK Day, plus two Fridays labeled in this list: January 12, 16 (Friday), 23 (Friday), 26, February 2, 9, 16, 23; labs each of those weeks on Wednesday, 4:30-6:45PM, Jan 14 - Feb 25. 

Course Description: :doc:`comp388`

COMP 388-5: Foundations of Comp Sci II
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**This course meets during the second 8 week session of the semester.**

Instructor: Peter L Dordal 

Time: See Note

Day(s): See Note 

Campus: Water Tower

Notes: Time and Days: Eight weeks after vacation, including two meetings in finals week. Mondays 5:30-9:30PM March 9 through April 27, Wednesdays 4:30-6:45PM March 11 through April 29.

Course Description: :doc:`comp388`

COMP 388-8: Research Methods in Comp Sci
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: TBD

Day(s): TBD 

Campus: Online

Course Description: :doc:`comp388`

COMP 388-9: Computational Neuroscience
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: 11:30 AM - 12:45 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp388`

COMP 391-01E: Internship in Computer Science
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp391`

COMP 398-01E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: George Thiruvathukal 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-02E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-03E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-04E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-05E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-06E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-07E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-08E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-09E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 398-10E: Independent Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp398`

COMP 399-1: Research Seminar
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: 12:35 PM - 1:25 PM

Day(s): Friday 

Campus: Lakeshore

Course Description: :doc:`comp399`

.. _graduate_courses_list:

Graduate Courses
~~~~~~~~~~~~~~~~~~

COMP 412-1: Free/Open Source Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Sharan Kalwani 

Time: 7:00 PM - 9:30 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp412`

COMP 413-1: Intermediate Object-Oriented Development
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: 7:00 PM - 9:30 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp413`

COMP 417-1: Social, Legal, and Ethical Issues in Computing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal 

Time: 4:15 PM - 6:45 PM

Day(s): Thursday 

Campus: Water Tower

Course Description: :doc:`comp417`

COMP 418-1: Combinatorial Mathematics
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Aaron Lauve 

Time: 10:25 AM - 11:15 AM

Day(s): Monday Wednesday Friday 

Campus: Lakeshore

Notes: Register for MATH 418-001

Course Description: :doc:`comp418`

COMP 441-1: Human-Computer Interface Design
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas Hayward 

Time: 7:00 PM - 9:30 PM

Day(s): Thursday 

Campus: Water Tower

Course Description: :doc:`comp441`

COMP 448-1: Network Security
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz 

Time: 5:30 PM - 8:00 PM

Day(s): Friday 

Campus: Water Tower

Course Description: :doc:`comp448`

COMP 448-2: Network Security
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Corby Schmitz 

Time: TBD

Day(s): TBD 

Campus: Online

Course Description: :doc:`comp448`

COMP 450-1: Microprogramming & Microprocessing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig 

Time: 1:00 PM - 2:15 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp450`

COMP 460-1: Algorithms and Complexity
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan 

Time: 4:15 PM - 6:45 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp460`

COMP 471-1: Programming Languages
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Konstantin Laufer 

Time: 4:15 PM - 6:45 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp471`

COMP 473-1: Object-Oriented Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Berhane Zewdie 

Time: 7:00 PM - 9:30 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp473`

COMP 474-1: Software Engineering
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig 

Time: 4:15 PM - 6:45 PM

Day(s): Thursday 

Campus: Water Tower

Course Description: :doc:`comp474`

COMP 477-1: IT Project Management
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Conrad Weisert 

Time: 4:15 PM - 6:45 PM

Day(s): Friday 

Campus: Water Tower

Course Description: :doc:`comp477`

COMP 484-1: Artificial Intelligence
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Conrad Weisert 

Time: 7:00 PM - 9:30 PM

Day(s): Monday 

Campus: Water Tower

Course Description: :doc:`comp484`

COMP 488-1: Data Warehousing and Data Mining
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: 4:15 PM - 6:45 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp488`

COMP 488-2: Database Administration
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal 

Time: 4:15 PM - 6:45 PM

Day(s): Tuesday 

Campus: Water Tower

Course Description: :doc:`comp488`

COMP 488-3: Computer Forensics
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Thomas Yarrish 

Time: 7:00 PM - 9:30 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp488`

COMP 488-9: Computational Neuroscience
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: 11:30 AM - 12:45 PM

Day(s): Tuesday Thursday 

Campus: Lakeshore

Course Description: :doc:`comp488`

COMP 488-10: Introduction to Digital Humanites Design and Programming
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Nicholas Hayward 

Time: 4:15 PM - 6:45 PM

Day(s): Wednesday 

Campus: Water Tower

Course Description: :doc:`comp488`

COMP 490-1: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: George Thiruvathukal 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-2: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Peter L Dordal 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-3: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Ronald I Greenberg 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-4: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-5: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: William Honig 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-6: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Catherine Putonti 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-7: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Chandra N Sekharan 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-8: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Robert Yacobellis 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-9: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Mark Albert 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 490-10: Independent Project
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Channah Naiman 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp490`

COMP 499-1: Internship
~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp499`

COMP 499-2: Internship
~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp499`

COMP 605-1: Master of Science Study
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Andrew N Harrington 

Time: TBD

Day(s): TBD 

Campus: Water Tower

Course Description: :doc:`comp605`

.. _csis_courses_list:

CSIS Courses
~~~~~~~~~~~~~~~~~~

CSIS 794-1: Managing Emerging Technologies
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Serhat Cicekoglu 

Time: 6:00 PM - 9:00 PM

Day(s): Monday 

Campus: Water Tower

Notes: Meeting Dates: 02/19/2015 - 05/09/2015

Course Description: :doc:`csis794`

CSIS 796-1: Data Warehousing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Abishek Sharma 

Time: 6:00 PM - 9:00 PM

Day(s): Monday 

Campus: Water Tower

Notes: Meeting Dates: 02/19/2015 - 05/09/2015

Course Description: :doc:`csis796`
