Spring 2015 Schedule (Widescreen/Table Format)
=============================================================

The following courses will (tentatively) be held during the Spring 2015 semester.

For classroom locations and open/full status, see `LOCUS <http://www.luc.edu/locus>`_.

Note: While we update this page regularly, please check `LOCUS <http://www.luc.edu/locus>`_ for the most recent information.

**In case of conflict, information on LOCUS should be considered authoritative.**

See `Textbook Information <https://docs.google.com/spreadsheet/ccc?key=0Aj_4VraMwHUodEdONlp1UW1tX203cURYV2dwQWl2VUE&usp=drive_web#gid=0>`_.

QuickLinks
~~~~~~~~~~~~~

* :doc:`spring2015mobile`
* :ref:`undergraduate_courses_table`
* :ref:`graduate_courses_table`
* :ref:`csis_courses_table`

.. _undergraduate_courses_table:

Undergraduate Courses
~~~~~~~~~~~~~~~~~~~~~~~~~~

:doc:`comp125`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Channah Naiman, 1:00 PM - 2:15 PM, TTr, Lakeshore, N/A 
    2, Channah Naiman, 4:15 PM - 6:45 PM, Tr, Lakeshore, N/A 

:doc:`comp150`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Zachary Romer, 2:30 PM - 3:45 PM, TTr, Lakeshore, N/A 
    2, Zachary Romer, 11:30 AM - 12:45 PM, TTr, Lakeshore, N/A 
    3, Curtis D Tuckey, 12:10 PM - 1:25 PM, MW, Lakeshore, N/A 

:doc:`comp163`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    2, Curtis D Tuckey, 4:15 PM - 5:30 PM, MW, Lakeshore, N/A 

:doc:`comp170`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Robert Yacobellis, 10:00 AM - 11:15 AM, TTr, Lakeshore, [#]_ 
    2, Andrew N Harrington, 1:00 PM - 2:15 PM, TTr, Lakeshore, [#]_ 
    3, Channah Naiman, 4:15 PM - 6:45 PM, T, Lakeshore, [#]_ 
    4, George Thiruvathukal, 10:25 AM - 11:15 AM, MWF, Lakeshore, [#]_ 
    01L, Robert Yacobellis, 11:30 AM - 11:55 AM, TTr, Lakeshore, [#]_ 
    02L, Andrew N Harrington, 12:20 PM - 12:45 PM, TTr, Lakeshore, [#]_ 
    03L, Channah Naiman, 7:00 PM - 7:45 PM, T, Lakeshore, [#]_ 
    04L, George Thiruvathukal, 11:30 AM - 11:55 AM, MW, Lakeshore, [#]_ 

.. rubric:: Notes

.. [#] Enrolling in this course will also enroll you in its lab section (01L). Meeting time is effectively 10:00 AM - 11:55 AM.
.. [#] Enrolling in this course will also enroll you in its lab section (02L). Meeting time is effectively 12:20 PM - 2:15 PM.

.. [#] Enrolling in this course will also enroll you in its lab section (03L). Meeting time is effectively 4:15 PM - 7:45 PM.

.. [#] Enrolling in this course will also enroll you in its lab section (04L). Meeting time is effectively 10:25 AM - 11:55 AM, except on Fridays when it is 10:25 AM - 11:15 AM.

.. [#] This is the lab section for 170-001.
.. [#] This is the lab section for 170-002.
.. [#] This is the lab section for 170-003.
.. [#] This is the lab section for 170-004.

:doc:`comp250`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    01W, Roxanne Schwab, 2:45 PM - 4:00 PM, MW, Lakeshore, N/A 
    02W, Roxanne Schwab, 7:00 PM - 9:30 PM, M, Lakeshore, N/A 

:doc:`comp251`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Guy Bevente, 7:00 PM - 9:30 PM, M, Lakeshore, N/A 

:doc:`comp264`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Ronald I Greenberg, 4:15 PM - 6:45 PM, Tr, Lakeshore, N/A 

:doc:`comp271`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Maria Saenz, 7:00 PM - 8:15 PM, TTr, Lakeshore, [#]_ 
    2, Catherine Putonti, 4:15 PM - 6:45 PM, W, Lakeshore, [#]_ 
    01L, Maria Saenz, 8:30 PM - 8:55 PM, TTr, Lakeshore, [#]_ 
    02L, Catherine Putonti, 7:00 PM - 7:50 PM, W, Lakeshore, [#]_ 

.. rubric:: Notes

.. [#] Enrolling in this course will also enroll you in its lab section (01L). Meeting time is effectively 7:00 PM - 8:55 PM.
.. [#] Enrolling in this course will also enroll you in its lab section (02L). Meeting time is effectively 4:15 PM - 7:50 PM.
.. [#] This is the lab section for 271-001.
.. [#] This is the lab section for 271-002.

:doc:`comp300`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Channah Naiman, 4:15 PM - 6:45 PM, W, Water Tower, N/A 

:doc:`comp305`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Peter L Dordal, 4:15 PM - 6:45 PM, T, Water Tower, N/A 

:doc:`comp312`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    01E, Sharan Kalwani, 7:00 PM - 9:30 PM, W, Water Tower, N/A 

:doc:`comp313`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Robert Yacobellis, 2:30 PM - 3:45 PM, TTr, Lakeshore, N/A 

:doc:`comp317`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Matthew Paul Butcher, TBD, TBD, Online, [#]_ 

.. rubric:: Notes

.. [#] This is an online class.  All lectures will be pre-recorded. Students are asked to attend smaller-group online interactive discussions at regular intervals during the semester, with possible times chosen to fit different groups' schedules.

:doc:`comp330`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, William Honig, 4:15 PM - 6:45 PM, T, Lakeshore, N/A 

:doc:`comp340`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Thomas Yarrish, 7:00 PM - 9:30 PM, W, Water Tower, N/A 

:doc:`comp348`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Corby Schmitz, 5:30 PM - 8:00 PM, F, Water Tower, N/A 
    2, Corby Schmitz, TBD, TBD, Online, N/A 

:doc:`comp353`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Chandra N Sekharan, 4:15 PM - 6:45 PM, M, Lakeshore, N/A 

:doc:`comp366`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, William Honig, 1:00 PM - 2:15 PM, TTr, Lakeshore, N/A 

:doc:`comp372`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Konstantin Laufer, 4:15 PM - 6:45 PM, W, Water Tower, N/A 

:doc:`comp373`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Berhane Zewdie, 7:00 PM - 9:30 PM, T, Water Tower, N/A 

:doc:`comp378`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Conrad Weisert, 7:00 PM - 9:30 PM, M, Water Tower, N/A 

:doc:`comp388`
----------------

.. csv-table::
    :header: "Section", "Topic", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 100, 75, 75, 30, 50, 50

    1, Human-Computer Interface Design, Nicholas Hayward, 7:00 PM - 9:30 PM, Tr, Water Tower, N/A 
    2, Advanced Algorithms & Complexity, Chandra N Sekharan, 4:15 PM - 6:45 PM, T, Water Tower, [#]_ 
    3, IT Project Management, Conrad Weisert, 4:15 PM - 6:45 PM, F, Water Tower, N/A 
    4, Foundations of Comp Sci I, Andrew N Harrington, See Note, See Note, Water Tower, [#]_ 
    5, Foundations of Comp Sci II, Peter L Dordal, See Note, See Note, Water Tower, [#]_ 
    8, Research Methods in Comp Sci, Mark Albert, TBD, TBD, Online, N/A 
    9, Computational Neuroscience, Mark Albert, 11:30 AM - 12:45 PM, TTr, Lakeshore, N/A 

.. rubric:: Notes

.. [#] prerequisite: COMP 363
.. [#] Time and Days: Seven weeks from start of semester, ending before vacation week. Classes 5:30-9:30PM all Mondays except MLK Day, plus two Fridays labeled in this list: January 12, 16 (Friday), 23 (Friday), 26, February 2, 9, 16, 23; labs each of those weeks on Wednesday, 4:30-6:45PM, Jan 14 - Feb 25. 
.. [#] Time and Days: Eight weeks after vacation, including two meetings in finals week. Mondays 5:30-9:30PM March 9 through April 27, Wednesdays 4:30-6:45PM March 11 through April 29.

:doc:`comp391`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    01E, Ronald I Greenberg, TBD, TBD, Water Tower, N/A 

:doc:`comp398`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    01E, George Thiruvathukal, TBD, TBD, Water Tower, N/A 
    02E, Peter L Dordal, TBD, TBD, Water Tower, N/A 
    03E, Ronald I Greenberg, TBD, TBD, Water Tower, N/A 
    04E, Andrew N Harrington, TBD, TBD, Water Tower, N/A 
    05E, William Honig, TBD, TBD, Water Tower, N/A 
    06E, Catherine Putonti, TBD, TBD, Water Tower, N/A 
    07E, Chandra N Sekharan, TBD, TBD, Water Tower, N/A 
    08E, Robert Yacobellis, TBD, TBD, Water Tower, N/A 
    09E, Mark Albert, TBD, TBD, Water Tower, N/A 
    10E, Channah Naiman, TBD, TBD, Water Tower, N/A 

:doc:`comp399`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Mark Albert, 12:35 PM - 1:25 PM, F, Lakeshore, N/A 

.. _graduate_courses_table:

Graduate Courses
~~~~~~~~~~~~~~~~~~

:doc:`comp412`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Sharan Kalwani, 7:00 PM - 9:30 PM, W, Water Tower, N/A 

:doc:`comp413`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Robert Yacobellis, 7:00 PM - 9:30 PM, T, Water Tower, N/A 

:doc:`comp417`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Peter L Dordal, 4:15 PM - 6:45 PM, Tr, Water Tower, N/A 

:doc:`comp418`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Aaron Lauve, 10:25 AM - 11:15 AM, MWF, Lakeshore, [#]_ 

.. rubric:: Notes

.. [#] Register for MATH 418-001

:doc:`comp441`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Nicholas Hayward, 7:00 PM - 9:30 PM, Tr, Water Tower, N/A 

:doc:`comp448`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Corby Schmitz, 5:30 PM - 8:00 PM, F, Water Tower, N/A 
    2, Corby Schmitz, TBD, TBD, Online, N/A 

:doc:`comp450`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, William Honig, 1:00 PM - 2:15 PM, TTr, Lakeshore, N/A 

:doc:`comp460`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Chandra N Sekharan, 4:15 PM - 6:45 PM, T, Water Tower, N/A 

:doc:`comp471`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Konstantin Laufer, 4:15 PM - 6:45 PM, W, Water Tower, N/A 

:doc:`comp473`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Berhane Zewdie, 7:00 PM - 9:30 PM, T, Water Tower, N/A 

:doc:`comp474`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, William Honig, 4:15 PM - 6:45 PM, Tr, Water Tower, N/A 

:doc:`comp477`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Conrad Weisert, 4:15 PM - 6:45 PM, F, Water Tower, N/A 

:doc:`comp484`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Conrad Weisert, 7:00 PM - 9:30 PM, M, Water Tower, N/A 

:doc:`comp488`
----------------

.. csv-table::
    :header: "Section", "Topic", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 100, 75, 75, 30, 50, 50

    1, Data Warehousing and Data Mining, Channah Naiman, 4:15 PM - 6:45 PM, W, Water Tower, N/A 
    2, Database Administration, Peter L Dordal, 4:15 PM - 6:45 PM, T, Water Tower, N/A 
    3, Computer Forensics, Thomas Yarrish, 7:00 PM - 9:30 PM, W, Water Tower, N/A 
    9, Computational Neuroscience, Mark Albert, 11:30 AM - 12:45 PM, TTr, Lakeshore, N/A 
    10, Introduction to Digital Humanites Design and Programming, Nicholas Hayward, 4:15 PM - 6:45 PM, W, Water Tower, N/A 

:doc:`comp490`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, George Thiruvathukal, TBD, TBD, Water Tower, N/A 
    2, Peter L Dordal, TBD, TBD, Water Tower, N/A 
    3, Ronald I Greenberg, TBD, TBD, Water Tower, N/A 
    4, Andrew N Harrington, TBD, TBD, Water Tower, N/A 
    5, William Honig, TBD, TBD, Water Tower, N/A 
    6, Catherine Putonti, TBD, TBD, Water Tower, N/A 
    7, Chandra N Sekharan, TBD, TBD, Water Tower, N/A 
    8, Robert Yacobellis, TBD, TBD, Water Tower, N/A 
    9, Mark Albert, TBD, TBD, Water Tower, N/A 
    10, Channah Naiman, TBD, TBD, Water Tower, N/A 

:doc:`comp499`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Andrew N Harrington, TBD, TBD, Water Tower, N/A 
    2, Andrew N Harrington, TBD, TBD, Water Tower, N/A 

:doc:`comp605`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Andrew N Harrington, TBD, TBD, Water Tower, N/A 

.. _csis_courses_table:

CSIS Courses
~~~~~~~~~~~~~~~~~~

:doc:`csis794`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Serhat Cicekoglu, 6:00 PM - 9:00 PM, M, Water Tower, [#]_ 

.. rubric:: Notes

.. [#] Meeting Dates: 02/19/2015 - 05/09/2015

:doc:`csis796`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Abishek Sharma, 6:00 PM - 9:00 PM, M, Water Tower, [#]_ 

.. rubric:: Notes

.. [#] Meeting Dates: 02/19/2015 - 05/09/2015
