Spring 2016 Schedule (Widescreen/Table Format)
=============================================================

The following courses will (tentatively) be held during the Spring 2016 semester.

For classroom locations and open/full status, see `LOCUS <http://www.luc.edu/locus>`_.

Note: While we update this page regularly, please check `LOCUS <http://www.luc.edu/locus>`_ for the most recent information.

**In case of conflict, information on LOCUS should be considered authoritative.**

QuickLinks
~~~~~~~~~~~~~

* :doc:`springmobile`
* :ref:`undergraduate_courses_table`
* :ref:`graduate_courses_table`
* :ref:`csis_courses_table`

.. _undergraduate_courses_table:

Undergraduate Courses
~~~~~~~~~~~~~~~~~~~~~~~~~~

:doc:`comp111`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    01W, George Thiruvathukal, 11:30 AM - 12:20 PM, MWF, Lakeshore, N/A 

:doc:`comp125`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Channah Naiman, 1:00 PM - 2:15 PM, TTr, Lakeshore, N/A 
    2, Guy Bevente, 7:00 PM - 9:30 PM, Tr, Lakeshore, N/A 

:doc:`comp150`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Andrew N Harrington, 2:30 PM - 4:00 PM, T, Lakeshore, See note [#]_ 
    2, TBD, 7:00 PM - 9:30 PM, W, Lakeshore, N/A 
    3, Heather E. Wheeler, 12:10 PM - 1:25 PM, MW, Lakeshore, N/A 

.. rubric:: Notes

.. [#] Harrington's section: This class has run successfully both face to face and online, with the same content.  This blended format takes advantage of face-to-face in initially getting to know each other, getting the class going, finding partners, and getting direct help with any online technology.  Later, since the class is flipped, and most all interaction is help on your individual computer work, help can come online, either in part of regular class time or at varied times convenient to you and the instructor.  We will use software to share screens online.  A quiet place is important for online help, with a computer that you have access to having good Internet speed and with the ability to talk and listen online.  


:doc:`comp163`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, TBD, 2:45 PM - 4:00 PM, MW, Lakeshore, N/A 
    2, TBD, 4:15 PM - 5:30 PM, MW, Lakeshore, N/A 

:doc:`comp170`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Robert Yacobellis, 10:00 AM - 11:15 AM, TTr, Lakeshore, N/A 
    2, Dmitriy Dligach, 10:25 AM - 11:40 AM, MW, Lakeshore, N/A 
    3, Maria Del Carmen Saenz, 6:00 PM - 8:30 PM, T, Lakeshore, N/A 
    4, Dmitriy Dligach, 12:10 PM - 1:25 PM, MW, Lakeshore, N/A 
    01L, Robert Yacobellis, 11:30 AM - 11:55 AM, TTr, Lakeshore, N/A 
    02L, Dmitriy Dligach, 10:25 AM - 11:15 AM, F, Lakeshore, N/A 
    03L, Maria Del Carmen Saenz, 8:30 PM - 9:20 PM, T, Lakeshore, N/A 
    04L, Dmitriy Dligach, 12:35 PM - 1:25 PM, F, Lakeshore, N/A 

:doc:`comp250`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    01W, Roxanne Schwab, 2:45 PM - 4:00 PM, MW, Lakeshore, N/A 
    02W, Roxanne Schwab, 7:00 PM - 9:30 PM, M, Lakeshore, N/A 

:doc:`comp264`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Ronald I Greenberg, 9:20 AM - 10:10 AM, MWF, Lakeshore, N/A 

:doc:`comp271`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Catherine Putonti, 2:30 PM - 3:45 PM, TTr, Lakeshore, N/A 
    2, Catherine Putonti, 4:15 PM - 6:45 PM, W, Lakeshore, N/A 
    01L, Catherine Putonti, 3:45 PM - 4:05 PM, TTr, Lakeshore, N/A 
    02L, Catherine Putonti, 7:00 PM - 7:50 PM, W, Lakeshore, N/A 

:doc:`comp300`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Channah Naiman, 4:15 PM - 6:45 PM, W, Water Tower, N/A 
    2, Channah Naiman, TBD, TBD, Online, [#]_ 

.. rubric:: Notes

.. [#] This class is a totally online asynchronous course.  Exams may be synchronous.  Combined with COMP 488-302.

:doc:`comp305`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Peter L Dordal, 4:15 PM - 6:45 PM, T, Water Tower, N/A 

:doc:`comp312`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    01E, TBD, 7:00 PM - 9:30 PM, W, Water Tower, N/A 

:doc:`comp313`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Robert Yacobellis, 1:00 PM - 2:15 PM, TTr, Lakeshore, N/A 

:doc:`comp317`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Matthew Paul Butcher, TBD, TBD, Online, [#]_ 
    01W, Roxanne Schwab, 7:00 PM - 9:30 PM, M, Lakeshore, N/A 

.. rubric:: Notes

.. [#] This is an online class.  All lectures will be pre-recorded.  Students are asked to attend smaller-group online interactive discussions at regular intervals during the semester with possible times chosen to fit different groups' schedules.

:doc:`comp319`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Jose Luis Gahete Diaz, 1:40 PM - 2:30 PM, F, Lakeshore, N/A 

:doc:`comp324`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Nicholas J Hayward, 4:15 PM - 6:45 PM, M, Water Tower, N/A 

:doc:`comp330`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, George Thiruvathukal, 6:00 PM - 8:30 PM, Tr, Lakeshore, N/A 

:doc:`comp339`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Sarah Kaylor, 7:00 PM - 9:30 PM, M, Lakeshore, N/A 

:doc:`comp340`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Thomas Yarrish, 7:00 PM - 9:30 PM, W, Water Tower, N/A 

:doc:`comp341`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Nicholas J Hayward, 7:00 PM - 9:30 PM, Tr, Water Tower, N/A 

:doc:`comp348`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Corby Schmitz, 5:30 PM - 8:00 PM, F, Water Tower, N/A 
    2, Corby Schmitz, TBD, TBD, Online, [#]_ 

.. rubric:: Notes

.. [#] This is an online class.  The classroom session will be broadcast live on Friday evenings via AdobeConnect allowing online student interaction.  Sessions will also be recorded and made available.  Students may participate synchronously or asynchronously at their discretion.  Combined with COMP 448-002.

:doc:`comp353`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Chandra N Sekharan, 4:15 PM - 6:45 PM, M, Lakeshore, N/A 

:doc:`comp363`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Mark Albert, 2:45 PM - 5:15 PM, Tr, Lakeshore, N/A 

:doc:`comp372`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Konstantin Laufer, 2:45 PM - 5:15 PM, W, Lakeshore, N/A 

:doc:`comp373`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Berhane Zewdie, 7:00 PM - 9:30 PM, T, Water Tower, N/A 

:doc:`comp377`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Conrad Weisert, 4:15 PM - 6:45 PM, F, Water Tower, N/A 

:doc:`comp378`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Conrad Weisert, 2:45 PM - 5:15 PM, M, Lakeshore, N/A 

:doc:`comp383`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Heather E. Wheeler, 2:45 PM - 4:05 PM, MW, Lakeshore, N/A 

:doc:`comp388`
----------------

.. csv-table::
    :header: "Section", "Topic", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 100, 75, 75, 30, 50, 50

    4, Foundations of Computer Science I, Andrew N Harrington, See Note, See Note, Water Tower, See note [#]_  
    5, Foundations of Computer Science II, Peter L Dordal, See Note, See Note, Water Tower, See note [#]_  
    6, Prog Lang and Systems Seminar, Jose Luis Gahete Diaz, 2:45 PM - 4:00 PM, F, Lakeshore, N/A 
    7, Physical Design and Fabrication, TBD, 7:00 PM - 9:30 PM, M, Lakeshore, N/A 

.. rubric:: Notes

.. [#] Eight Week-First Session.  This section is restricted to students with undergraduate degrees.  Department Consent required, and then a Computer Science Department staff member will enroll you.  FIRST CLASS EARLY:  Friday before other classes start:  Friday, January 15!  And then on for the next seven weeks, ending before vacation week.  Classes meet from 4:15 pm - 8:15 pm on Fri, Jan 15, and Fri, Jan 22.  And then, 4:15 pm- 8:15 pm for the next 6 Mondays:  Jan 25, Feb 1, Feb 8, Feb 15, Feb 22, Feb 29.  Labs meet on Wednesdays, 4:15 pm - 6:30 pm:  Jan 20, Jan 27, Feb 3, Feb 10, Feb 17, Feb 24, Mar 2.

.. [#] Eight Week-Second Session.  This section is restricted to students with undergraduate degrees.  Department Consent required, and then a Computer Science Department staff member will enroll you.  Eight weeks after vacation, including two meetings in finals week.  Mondays, 4:15 pm -8:15 pm:  March 14, March 21, March 28, April 4, April 11, April 18, April 25, May 2.  Labs meet on Wednesdays, 4:15 pm - 6:30 pm:  March 16, March 23, March 30, April 6, April 13, April 20, April 27, May 4.

:doc:`comp391`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    01E, Ronald I Greenberg, TBD, TBD, Water Tower, N/A 

:doc:`comp397`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    8, Mark Albert, TBD, TBD, Online, [#]_ 

.. rubric:: Notes

.. [#] The Computer Science Seminar course and the Research Seminar course will meet on alternate weeks at the scheduled course time.

:doc:`comp398`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    01E, Konstantin Laufer, TBD, TBD, Water Tower, N/A 
    02E, Mark Albert, TBD, TBD, Water Tower, N/A 
    03E, Dmitriy Dligach, TBD, TBD, Water Tower, N/A 
    04E, Peter L Dordal, TBD, TBD, Water Tower, N/A 
    05E, Ronald I Greenberg, TBD, TBD, Water Tower, N/A 
    06E, Andrew N Harrington, TBD, TBD, Water Tower, N/A 
    07E, Nicholas J Hayward, TBD, TBD, Water Tower, N/A 
    08E, William Honig, TBD, TBD, Water Tower, N/A 
    09E, Channah Naiman, TBD, TBD, Water Tower, N/A 
    10E, Catherine Putonti, TBD, TBD, Water Tower, N/A 
    11E, Chandra N Sekharan, TBD, TBD, Water Tower, N/A 
    12E, Heather E. Wheeler, TBD, TBD, Water Tower, N/A 
    13E, Robert Yacobellis, TBD, TBD, Water Tower, N/A 

:doc:`comp399`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Mark Albert, 11:30 AM - 12:45 PM, T, Lakeshore, N/A 

.. _graduate_courses_table:

Graduate Courses
~~~~~~~~~~~~~~~~~~

:doc:`comp412`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, TBD, 7:00 PM - 9:30 PM, W, Water Tower, N/A 

:doc:`comp413`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Robert Yacobellis, 4:15 PM - 6:45 PM, T, Water Tower, N/A 

:doc:`comp417`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Peter L Dordal, 4:15 PM - 6:45 PM, Tr, Water Tower, N/A 

:doc:`comp424`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Nicholas J Hayward, 4:15 PM - 6:45 PM, M, Water Tower, N/A 

:doc:`comp439`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Sarah Kaylor, 7:00 PM - 9:30 PM, M, Lakeshore, N/A 

:doc:`comp441`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Nicholas J Hayward, 7:00 PM - 9:30 PM, Tr, Water Tower, N/A 

:doc:`comp448`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Corby Schmitz, 5:30 PM - 8:00 PM, F, Water Tower, N/A 
    2, Corby Schmitz, TBD, TBD, Online, [#]_ 

.. rubric:: Notes

.. [#] This is an online class.  The classroom session will be broadcast live on Friday evenings via AdobeConnect allowing online student interaction.  Sessions will also be recorded and made available.  Students may participate synchronously or asynchronously at their discretion.  Combined with COMP 348-002.

:doc:`comp460`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Chandra N Sekharan, 2:45 PM - 5:15 PM, T, Lakeshore, N/A 

:doc:`comp471`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Konstantin Laufer, 2:45 PM - 5:15 PM, W, Lakeshore, N/A 

:doc:`comp473`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Berhane Zewdie, 7:00 PM - 9:30 PM, T, Water Tower, N/A 

:doc:`comp474`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, TBD, 7:00 PM - 9:30 PM, Tr, Water Tower, N/A 

:doc:`comp477`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Conrad Weisert, 4:15 PM - 6:45 PM, F, Water Tower, N/A 

:doc:`comp484`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Conrad Weisert, 2:45 PM - 5:15 PM, M, Lakeshore, N/A 

:doc:`comp488`
----------------

.. csv-table::
    :header: "Section", "Topic", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 100, 75, 75, 30, 50, 50

    7, Physical Design and Fabrication, TBD, 7:00 PM - 9:30 PM, M, Lakeshore, N/A 
    301, Data Warehousing and Data Mining, Channah Naiman, 4:15 PM - 6:45 PM, W, Water Tower, N/A 
    302, Data Warehousing and Data Mining, Channah Naiman, TBD, TBD, Online, [#]_ 
    305, Database Administration, Peter L Dordal, 4:15 PM - 6:45 PM, T, Water Tower, N/A 
    340, Computer Forensics, Thomas Yarrish, 7:00 PM - 9:30 PM, W, Water Tower, N/A 
    383, Computational Biology, Heather E. Wheeler, 2:45 PM - 4:05 PM, MW, Lakeshore, N/A 
    402, Intro Digital Humanities Design & Programming, Nicholas J Hayward, 4:15 PM - 6:45 PM, W, Water Tower, N/A 

.. rubric:: Notes

.. [#] This class is a totally online asynchronous course.  Exams may be synchronous.  Combined with COMP 300-002.

:doc:`comp490`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Konstantin Laufer, TBD, TBD, Water Tower, N/A 
    2, Mark Albert, TBD, TBD, Water Tower, N/A 
    3, Dmitriy Dligach, TBD, TBD, Water Tower, N/A 
    4, Peter L Dordal, TBD, TBD, Water Tower, N/A 
    5, Ronald I Greenberg, TBD, TBD, Water Tower, N/A 
    6, Andrew N Harrington, TBD, TBD, Water Tower, N/A 
    7, Nicholas J Hayward, TBD, TBD, Water Tower, N/A 
    8, William Honig, TBD, TBD, Water Tower, N/A 
    9, Channah Naiman, TBD, TBD, Water Tower, N/A 
    10, Catherine Putonti, TBD, TBD, Water Tower, N/A 
    11, Chandra N Sekharan, TBD, TBD, Water Tower, N/A 
    12, Heather E. Wheeler, TBD, TBD, Water Tower, N/A 
    13, Robert Yacobellis, TBD, TBD, Water Tower, N/A 

:doc:`comp499`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Konstantin Laufer, TBD, TBD, Water Tower, N/A 

:doc:`comp605`
----------------

.. csv-table::
    :header: "Section", "Instructor", "Time", "Day(s)", "Campus", "Note"
    :widths: 10, 175, 75, 30, 50, 50

    1, Konstantin Laufer, TBD, TBD, Water Tower, N/A 

.. _csis_courses_table:

CSIS Courses
~~~~~~~~~~~~~~~~~~

No CSIS Courses Currently Available.