.. _csis_courses_list:

CSIS Courses
~~~~~~~~~~~~~~~~~

CSIS 794-1: Managing Emerging Technologies
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Serhat Cicekoglu

Time: 6:00 PM - 9:00 PM

Day(s): Monday

Campus: Water Tower

Course Description: :doc:`csis794`

CSIS 796-1: Data Warehousing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instructor: Abhishek Sharma 

Time: 6:00 PM - 9:00 PM

Day(s): Monday

Campus: Water Tower

Course Description: :doc:`csis796`
