Summer 2015 - Schedule
=============================

The CAS has posted the course schedule for Summer 2015. The schedule can be found here: http://www.luc.edu/summer/courses/cas/ (scroll down the page to the Computer Science Schedule).

Please Note:

* Computer Science Graduate Courses **are listed** on the Summer Schedule despite the page stating otherwise.
* Independent Study and Internships can be taken during any session (A, B, or C) with B being the most popular choice as grades are posted later.
