Features Common to all Programs
  * See the :doc:`masters_prereqs`.
  * Each program requires a total of 30 credit hours, generally 10 three-credit courses. 
  * Students can receive up to 6 credit hours (replacing two of our courses) 
    for graduate work taken elsewhere: See the `transfer credit section of the Graduate Student Handbook <http://gradhandbook.cs.luc.edu/html/regulations.html#transfer-credit>`_ for details. 
  * **Students who have taken undergraduate Loyola classes**: 
    Many 400-level courses in the department have closely related 300-level analogues, 
    e.g. :doc:`comp443` and :doc:`comp343`. Students who enter the MS program after taking 
    a Loyola course in this category 
    must choose to take 400-level courses that are not closely related to any 
    300-level courses taken earlier, unless they have GPD permission.
